#!/bin/sh

set -eu

script_directory=$(CDPATH= cd "$(dirname "$0")" && pwd)
repository_path=${CI_PRIMARY_REPOSITORY_PATH:-$(CDPATH= cd "$script_directory/../.." && pwd)}
output_path="$repository_path/client/CiJing/Core/GeneratedClientConfig.swift"

strip_surrounding_quotes() {
    value=$1
    case "$value" in
        \"*\") value=${value#\"}; value=${value%\"} ;;
        \'*\') value=${value#\'}; value=${value%\'} ;;
        “*”) value=${value#“}; value=${value%”} ;;
        ‘*’) value=${value#‘}; value=${value%’} ;;
    esac
    printf '%s' "$value"
}

# Match scripts/load-env.mjs so values copied from a quoted .env entry behave
# the same way locally and in Xcode Cloud.
supabase_url=$(strip_surrounding_quotes "${SUPABASE_URL:-}")
supabase_publishable_key=$(strip_surrounding_quotes "${SUPABASE_PUBLISHABLE_KEY:-${SUPABASE_ANON_KEY:-}}")

if [ -z "$supabase_url" ]; then
    echo "error: SUPABASE_URL is not configured for this Xcode Cloud workflow." >&2
    exit 1
fi

if [ -z "$supabase_publishable_key" ]; then
    echo "error: SUPABASE_PUBLISHABLE_KEY is not configured for this Xcode Cloud workflow." >&2
    exit 1
fi

# These values become Swift string literals. Restrict them to the character sets
# used by Supabase URLs and publishable/legacy anon keys before interpolation.
if ! printf '%s' "$supabase_url" | grep -Eq '^https://[A-Za-z0-9.-]+(:[0-9]+)?(/[^"[:space:]]*)?$'; then
    echo "error: SUPABASE_URL must be a valid HTTPS URL without quotes or whitespace." >&2
    exit 1
fi

if ! printf '%s' "$supabase_publishable_key" | grep -Eq '^[A-Za-z0-9._-]+$'; then
    echo "error: SUPABASE_PUBLISHABLE_KEY contains unsupported characters." >&2
    exit 1
fi

cat > "$output_path" <<EOF
// Generated by client/ci_scripts/ci_post_clone.sh. Do not edit directly.
enum GeneratedClientConfig {
    static let SUPABASE_URL = "$supabase_url"
    static let SUPABASE_PUBLISHABLE_KEY = "$supabase_publishable_key"
}
EOF

echo "Generated client/CiJing/Core/GeneratedClientConfig.swift for Xcode Cloud."
