import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { readEnvFile, setEnvValue } from "./load-env.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, ".env");
const isCheck = process.argv.includes("--check");
const useLocalDeviceAddress = process.argv.includes("--local-device");
const urlIndex = process.argv.indexOf("--url");
let requestedURL = urlIndex >= 0 ? process.argv[urlIndex + 1] : undefined;
let localDeviceURL;

if (urlIndex >= 0 && !requestedURL) {
  throw new Error("--url 后需要提供完整地址，例如 https://YOUR_PROJECT.supabase.co");
}
if (isCheck && requestedURL) {
  throw new Error("--check 不能与 --url 同时使用");
}
if (isCheck && useLocalDeviceAddress) {
  throw new Error("--check 不能与 --local-device 同时使用");
}
if (requestedURL && useLocalDeviceAddress) {
  throw new Error("--url 不能与 --local-device 同时使用");
}

if (useLocalDeviceAddress) {
  let localHost = process.env.CIJING_LOCAL_SERVER_HOST?.trim();
  if (!localHost) {
    try {
      const bonjourName = execFileSync("/usr/sbin/scutil", ["--get", "LocalHostName"], { encoding: "utf8" }).trim();
      if (bonjourName) localHost = `${bonjourName}.local`;
    } catch {
      // Fall back to the current interface address on systems without scutil.
    }
  }
  if (!localHost) {
    const interfaceName = process.env.CIJING_NETWORK_INTERFACE || "en0";
    const addresses = os.networkInterfaces()[interfaceName] || [];
    const localIPv4 = addresses.find((entry) =>
      entry.family === "IPv4"
        && !entry.internal
        && !entry.address.startsWith("169.254.")
    );
    if (!localIPv4) {
      throw new Error(
        `未能读取 Mac 的 Bonjour 名称或 ${interfaceName} IPv4 地址。请检查网络，或设置 CIJING_LOCAL_SERVER_HOST。`
      );
    }
    localHost = localIPv4.address;
  }

  const port = process.env.CIJING_LOCAL_SERVER_PORT || "8000";
  if (!/^\d+$/.test(port) || Number(port) < 1 || Number(port) > 65535) {
    throw new Error("CIJING_LOCAL_SERVER_PORT 必须是 1 到 65535 之间的端口号");
  }

  localDeviceURL = `http://${localHost}:${port}`;
  console.log(`真机将连接本机 Flask：${localDeviceURL}`);
}

let config = readEnvFile(sourcePath);

if (requestedURL) {
  const parsed = new URL(requestedURL);
  if (!["http:", "https:"].includes(parsed.protocol) || !parsed.hostname || parsed.username || parsed.password) {
    throw new Error("SUPABASE_URL 必须是没有账号信息的 http(s) 地址");
  }
  if (parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("SUPABASE_URL 只应包含协议、主机和端口");
  }
  config.SUPABASE_URL = parsed.toString().replace(/\/$/, "");
  setEnvValue(sourcePath, "SUPABASE_URL", config.SUPABASE_URL);
  config = readEnvFile(sourcePath);
}

const publishableKey = config.SUPABASE_PUBLISHABLE_KEY || config.SUPABASE_ANON_KEY;

if (typeof config.SUPABASE_URL !== "string" || !config.SUPABASE_URL.trim()) {
  throw new Error("SUPABASE_URL 不能为空");
}
if (typeof publishableKey !== "string" || !publishableKey.trim()) {
  throw new Error("SUPABASE_PUBLISHABLE_KEY 不能为空");
}
const iosURL = localDeviceURL || config.SUPABASE_URL;
const outputs = new Map([
  [path.join(root, "extension/shared/generated-client-config.js"),
`// Generated by scripts/generate-config.mjs from .env. Do not edit directly.
export const SUPABASE_URL = ${JSON.stringify(config.SUPABASE_URL)};
export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)};
`],
  [path.join(root, "client/CiJing/Core/GeneratedClientConfig.swift"),
`// Generated by scripts/generate-config.mjs from .env. Do not edit directly.
enum GeneratedClientConfig {
    static let SUPABASE_URL = ${JSON.stringify(iosURL)}
    static let SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)}
}
`]
]);

let stale = false;
for (const [outputPath, expected] of outputs) {
  if (isCheck) {
    if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== expected) {
      console.error(`配置未同步：${path.relative(root, outputPath)}`);
      stale = true;
    }
  } else {
    fs.writeFileSync(outputPath, expected);
    console.log(`已生成 ${path.relative(root, outputPath)}`);
  }
}

if (stale) {
  console.error("请运行 node scripts/generate-config.mjs");
  process.exitCode = 1;
}
