import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readEnvFile, setEnvValue } from "./load-env.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, ".env");
const isCheck = process.argv.includes("--check");
const urlIndex = process.argv.indexOf("--url");
const requestedURL = urlIndex >= 0 ? process.argv[urlIndex + 1] : undefined;

if (urlIndex >= 0 && !requestedURL) {
  throw new Error("--url 后需要提供完整地址，例如 http://192.168.1.20:54321");
}
if (isCheck && requestedURL) {
  throw new Error("--check 不能与 --url 同时使用");
}

let config = readEnvFile(sourcePath);

if (requestedURL) {
  const parsed = new URL(requestedURL);
  if (!["http:", "https:"].includes(parsed.protocol) || !parsed.hostname || parsed.username || parsed.password) {
    throw new Error("SUPABASE_URL 必须是没有账号信息的 http(s) 地址");
  }
  if (parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error("SUPABASE_URL 只应包含协议、主机和端口");
  }
  config.SUPABASE_URL = parsed.toString().replace(/\/$/, "");
  setEnvValue(sourcePath, "SUPABASE_URL", config.SUPABASE_URL);
  config = readEnvFile(sourcePath);
}

const publishableKey = config.SUPABASE_PUBLISHABLE_KEY || config.SUPABASE_ANON_KEY;

if (typeof config.SUPABASE_URL !== "string" || !config.SUPABASE_URL.trim()) {
  throw new Error("SUPABASE_URL 不能为空");
}
if (typeof publishableKey !== "string" || !publishableKey.trim()) {
  throw new Error("SUPABASE_PUBLISHABLE_KEY 不能为空");
}
const outputs = new Map([
  [path.join(root, "extension/shared/generated-client-config.js"),
`// Generated by scripts/generate-config.mjs from .env. Do not edit directly.
export const SUPABASE_URL = ${JSON.stringify(config.SUPABASE_URL)};
export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)};
`],
  [path.join(root, "client/CiJing/Core/GeneratedClientConfig.swift"),
`// Generated by scripts/generate-config.mjs from .env. Do not edit directly.
enum GeneratedClientConfig {
    static let SUPABASE_URL = ${JSON.stringify(config.SUPABASE_URL)}
    static let SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishableKey)}
}
`]
]);

let stale = false;
for (const [outputPath, expected] of outputs) {
  if (isCheck) {
    if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== expected) {
      console.error(`配置未同步：${path.relative(root, outputPath)}`);
      stale = true;
    }
  } else {
    fs.writeFileSync(outputPath, expected);
    console.log(`已生成 ${path.relative(root, outputPath)}`);
  }
}

if (stale) {
  console.error("请运行 node scripts/generate-config.mjs");
  process.exitCode = 1;
}
